/**
 * Re-exports from the auto-generated OpenCascade.js v2 type definitions.
 *
 * The canonical types live in `src/wasm/opencascade.d.ts`, generated by the
 * custom Docker build. This file provides convenience aliases used throughout
 * the codebase so existing imports continue to work.
 */

export type {
  OpenCascadeInstance,
  TopoDS_Shape as TopoDSShape,
  TopoDS_Face as TopoDSFace,
  TopoDS_Shell as TopoDSShell,
  TopoDS_Wire as TopoDSWire,
  TopoDS_Edge as TopoDSEdge,
  TopTools_ListOfShape as TopToolsListOfShape,
  BRepAlgoAPI_Fuse,
  BRepAlgoAPI_Cut,
  BRepAlgoAPI_Common,
} from '../wasm/opencascade'

/**
 * Emscripten virtual filesystem — available on the OpenCascadeInstance as `oc.FS`.
 * The generated types declare this as `typeof FS` which is a namespace;
 * we keep a simpler interface for the methods we actually use.
 */
export interface EmscriptenFS {
  readFile(path: string, opts?: { encoding?: string; flags?: string }): Uint8Array | string
  writeFile(path: string, data: string | ArrayBufferView, opts?: { flags?: string }): void
  unlink(path: string): void
}
